# src/AppBundle/Resources/config/doctrine/Userprofile.orm.yml
AppBundle\Entity\UserProfile:
    type:  entity
    table: user_profile
    uniqueConstraints:
        search_idx:
           columns: [ privatenum]
    id:
       id:
           type: integer
           generator:
              strategy: AUTO