# src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
    type:  entity
    table: users
    id:
       id:
           type: integer
           generator:
              strategy: AUTO
