<?php

namespace AppBundle\Repository;


/**
 * CityRepository   need to be revised
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{


}
