<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{

    public function listAll () {
        $qb = $this->createQueryBuilder('d')
            ->orderBy('d.name', 'ASC')
            ->getQuery();

        return $qb;
    }

}
