<?php

namespace AppBundle\Repository;

/**
 * EvtipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtipRepository extends \Doctrine\ORM\EntityRepository
{
}
