<?php

namespace AppBundle\Repository;

/**
 * SmiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmiRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll () {
        $qb = $this->createQueryBuilder('s')
            ->orderBy('s.title', 'ASC')
            ->getQuery();

        return $qb;
    }
}
