<?php

namespace AppBundle\Repository;

/**
 * SmitipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmitipRepository extends \Doctrine\ORM\EntityRepository
{
}
