<?php

namespace AppBundle\Repository;

/**
 * UserEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventRepository extends \Doctrine\ORM\EntityRepository
{
}
